<a href="https://colab.research.google.com/github/A01286962/1-maap/blob/main/A4_Pivot_Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
path_file = 'https://raw.githubusercontent.com/tec03/Datasets/0499cdd7fddd3e4c4ca6c50b463c70c5872d62a3/datasets/antropometria-dataset.csv'
df = pd.read_csv(path_file)
df.head()

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.4,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.1,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.0,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.5,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.0,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215

In [72]:
pivot = pd.pivot_table(df, values='peso', index='desc_ent', aggfunc='mean')
pivot

                                      peso
desc_ent
AGUASCALIENTES                   66.357786
BAJA CALIFORNIA                  68.467270
BAJA CALIFORNIA SUR              71.809198
CAMPECHE                         65.418475
CHIAPAS                          57.613775
CHIHUAHUA                        66.656005
COAHUILA DE ZARAGOZA             68.154142
COLIMA                           68.743648
DISTRITO FEDERAL                 65.119273
DURANGO                          66.354922
GUANAJUATO                       63.936390
GUERRERO                         60.466315
HIDALGO                          59.995917
JALISCO                          66.697270
MEXICO                           60.680850
MICHOACAN DE OCAMPO              64.900000
MORELOS                          63.541295
NAYARIT                          66.541827
NUEVO LEON                       67.239853
OAXACA                           58.800067
PUEBLA                           60.102996
QUERETARO                        63.547342
QUINTANA ROO                     64.238904
SAN LUIS POTOSI                  60.576912
SINALOA                          68.051272
SONORA                           68.849473
TABASCO                          66.554701
TAMAULIPAS                       68.210911
TLAXCALA                         62.085398
VERACRUZ DE IGNACIO DE LA LLAVE  62.546117
YUCATAN                          62.706315
ZACATECAS                        64.238524

# Question 1:

Average Weight of people from Morelos 63.541

In [73]:
pivot = pd.pivot_table(df, values='peso' , index= 'desc_ent', aggfunc='median',columns='sexo')
pivot

sexo                                   1        2
desc_ent
AGUASCALIENTES                   69.9500  63.7000
BAJA CALIFORNIA                  70.6500  64.2000
BAJA CALIFORNIA SUR              76.6500  68.5500
CAMPECHE                         67.3500  62.3750
CHIAPAS                          59.2000  56.0250
CHIHUAHUA                        69.3000  64.6250
COAHUILA DE ZARAGOZA             68.3000  67.3000
COLIMA                           71.7000  66.0000
DISTRITO FEDERAL                 69.0000  61.4500
DURANGO                          70.3500  62.5000
GUANAJUATO                       65.0625  60.3250
GUERRERO                         60.5000  57.2000
HIDALGO                          63.3000  57.9000
JALISCO                          65.5875  63.3500
MEXICO                           62.4500  56.9500
MICHOACAN DE OCAMPO              67.6250  63.4000
MORELOS                          65.2000  61.4500
NAYARIT                          69.0500  63.7000
NUEVO LEON                       69.4000  65.1000
OAXACA                           59.5500  56.8000
PUEBLA                           61.8750  59.5500
QUERETARO                        65.2750  59.4500
QUINTANA ROO                     65.9250  60.8500
SAN LUIS POTOSI                  62.2000  57.4500
SINALOA                          71.1000  64.3000
SONORA                           72.3000  66.6500
TABASCO                          69.7500  62.6000
TAMAULIPAS                       72.7500  63.3500
TLAXCALA                         64.2750  59.8750
VERACRUZ DE IGNACIO DE LA LLAVE  64.3000  59.4725
YUCATAN                          66.0000  59.5750
ZACATECAS                        65.3000  61.6250

# Question 2

median Weight of Sex 2 of Yucatan is 59.575

In [74]:
pivot = pd.pivot_table(df, values='peso' , index= 'desc_ent', aggfunc='mean',columns='sexo')
pivot

sexo                                     1          2
desc_ent
AGUASCALIENTES                   69.985381  63.254292
BAJA CALIFORNIA                  71.391818  65.893667
BAJA CALIFORNIA SUR              75.561015  68.168959
CAMPECHE                         68.622637  62.920493
CHIAPAS                          58.365222  57.096111
CHIHUAHUA                        68.892642  64.815295
COAHUILA DE ZARAGOZA             68.873094  67.467348
COLIMA                           70.998878  66.978393
DISTRITO FEDERAL                 69.460661  61.654128
DURANGO                          68.846451  64.400031
GUANAJUATO                       65.008000  63.100995
GUERRERO                         62.611437  58.899850
HIDALGO                          61.747958  58.972554
JALISCO                          67.076482  66.418111
MEXICO                           63.140314  58.887882
MICHOACAN DE OCAMPO              66.374612  63.784311
MORELOS                          65.741943  62.195391
NAYARIT                          68.822143  64.890564
NUEVO LEON                       70.168106  64.823014
OAXACA                           60.810332  57.450557
PUEBLA                           61.866875  58.820175
QUERETARO                        66.751233  60.860793
QUINTANA ROO                     65.149528  63.538000
SAN LUIS POTOSI                  62.614907  58.979163
SINALOA                          71.122911  65.565234
SONORA                           70.880406  67.024857
TABASCO                          69.255801  64.190187
TAMAULIPAS                       72.060601  64.866851
TLAXCALA                         64.784437  60.201164
VERACRUZ DE IGNACIO DE LA LLAVE  65.324094  60.565646
YUCATAN                          65.717541  60.537515
ZACATECAS                        66.096483  62.757788

#Question 3

Valor maximo de promedios del sexo 1 es 75.561

In [75]:
path_file = 'https://raw.githubusercontent.com/tec03/Datasets/0499cdd7fddd3e4c4ca6c50b463c70c5872d62a3/datasets/adult.csv'
df = pd.read_csv(path_file)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,the label
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [76]:
pivot_adult = pd.pivot_table(df, values=['hours-per-week','age'], index=['marital-status', 'education'], aggfunc='mean')

display(pivot_adult.xs(' HS-grad', level='education'))

                             age  hours-per-week
marital-status
Divorced               42.363918       40.668320
Married-AF-spouse      34.615385       43.000000
Married-civ-spouse     42.817131       42.635501
Married-spouse-absent  39.413223       39.661157
Never-married          28.533506       38.691162
Separated              38.266010       38.189655
Widowed                59.405797       32.693237
test_category_female   52.000000       40.000000
test_category_male     52.000000       40.000000

# Question 4

Promedio de Hours per week de divorciados con HS-grad es 40.668

In [77]:
pivot_adult = pd.pivot_table(df, values=['hours-per-week','age'], index=['marital-status', 'education'], columns='sex' ,aggfunc='median')

display(pivot_adult.xs(' Married-AF-spouse', level='marital-status'))

                age       hours-per-week
sex          Female  Male         Female  Male
education
Assoc-acdm     31.5   NaN           21.5   NaN
Assoc-voc       NaN  29.0            NaN  44.0
Bachelors      27.0  34.5           40.0  50.0
HS-grad        33.5  29.0           31.5  60.0
Some-college   28.0  26.0           40.0  40.0

#Question 5

median Hours per week for males with bachelors with Married-AF-Spouse marital status its 50